drop table if exists users, register_keys, avatars, accounts, types_account, payments, games, created_games cascade;
CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname   VARCHAR(20)                             NOT NULL,
    email      VARCHAR(60)                             NOT NULL,
    password   VARCHAR(200)                            NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    role       VARCHAR(10)                             NOT NULL,
    profession VARCHAR(50)                             NOT NULL,
    status     VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT uq_user_nickname UNIQUE (nickname)
);
CREATE TABLE IF NOT EXISTS register_keys
(
    register_key_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hash_key        VARCHAR(2000)                           NOT NULL,
    email           VARCHAR(60)                             NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    exp             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_register_keys PRIMARY KEY (register_key_id),
    CONSTRAINT fk_register_key_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS avatars
(
    avatar_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url VARCHAR(200),
    user_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_avatars PRIMARY KEY (avatar_id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE

);
CREATE TABLE IF NOT EXISTS accounts
(
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    amount     NUMERIC(14, 2)                          NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (account_id),
    CONSTRAINT fk_account_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS types_account
(
    types_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(50)                             NOT NULL,
    account_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_types_account PRIMARY KEY (types_account_id),
    CONSTRAINT uq_type_account_name UNIQUE (name),
    CONSTRAINT fk_account_id FOREIGN KEY (account_id) REFERENCES accounts (account_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS payments
(
    payments_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id_from BIGINT                                  NOT NULL,
    account_id_to   BIGINT                                  NOT NULL,
    amount          NUMERIC(14, 2)                          NOT NULL,
    created_on      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (payments_id),
    CONSTRAINT fk_account_id_from FOREIGN KEY (account_id_from) REFERENCES accounts (account_id),
    CONSTRAINT fk_account_id_to FOREIGN KEY (account_id_to) REFERENCES accounts (account_id)
);
CREATE TABLE IF NOT EXISTS games
(
    game_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(2500)                           NOT NULL,
    created_on  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_games PRIMARY KEY (game_id)
);
CREATE TABLE IF NOT EXISTS created_games
(
    game_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_game_id FOREIGN KEY (game_id) REFERENCES games (game_id),
    CONSTRAINT fk_created_games_user_id FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uq_user_id UNIQUE (user_id)
);